"""Initial schema

Revision ID: 03c4faa4a722
Revises: 
Create Date: 2025-11-26 12:14:38.562810+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c4faa4a722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('gps_lat', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('gps_lon', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_site_code'), 'sites', ['site_code'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('gps_lat', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('gps_lon', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'FLAGGED', name='submissionstatus'), nullable=False),
    sa.Column('surveyor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_site_id'), 'submissions', ['site_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_timestamp'), 'submissions', ['timestamp'], unique=False)
    op.create_table('ai_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('model_output', sa.JSON(), nullable=True),
    sa.Column('completion_percentages', sa.JSON(), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_results_model_type'), 'ai_results', ['model_type'], unique=False)
    op.create_index(op.f('ix_ai_results_stage'), 'ai_results', ['stage'], unique=False)
    op.create_index(op.f('ix_ai_results_submission_id'), 'ai_results', ['submission_id'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_flag_type'), 'fraud_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_fraud_flags_resolved'), 'fraud_flags', ['resolved'], unique=False)
    op.create_index(op.f('ix_fraud_flags_submission_id'), 'fraud_flags', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_flags_submission_id'), table_name='fraud_flags')
    op.drop_index(op.f('ix_fraud_flags_resolved'), table_name='fraud_flags')
    op.drop_index(op.f('ix_fraud_flags_flag_type'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_ai_results_submission_id'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_stage'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_model_type'), table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index(op.f('ix_submissions_timestamp'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_site_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_sites_site_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
