"""Add phash and is_approved to submissions

Revision ID: fed10a6638e2
Revises: 03c4faa4a722
Create Date: 2025-11-27 05:19:36.930912+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fed10a6638e2'
down_revision = '03c4faa4a722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_results', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('fraud_flags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sites', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sites', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('submissions', sa.Column('phash', sa.String(length=64), nullable=True))
    op.add_column('submissions', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.alter_column('submissions', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('submissions', 'surveyor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_submissions_is_approved'), 'submissions', ['is_approved'], unique=False)
    op.create_index(op.f('ix_submissions_phash'), 'submissions', ['phash'], unique=False)
    op.create_index(op.f('ix_submissions_surveyor_id'), 'submissions', ['surveyor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_surveyor_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_phash'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_is_approved'), table_name='submissions')
    op.alter_column('submissions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('submissions', 'surveyor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('submissions', 'is_approved')
    op.drop_column('submissions', 'phash')
    op.alter_column('sites', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('sites', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('fraud_flags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ai_results', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
